### ISSUE TITLE
No License file

### ISSUE THREAD

**Issue by oscarvalenzuelab** [akidee/hash.js#1]
Hey,

I was planning to use this package in one of my projects, but I'm not sure what license you are using.
You have MIT in your other repos, should I consider this package under MIT as well?

Thanks,
Oscar

**Comment by akidee** [comment]
Yes, it`s under MIT license, like the others. If you need it in the repo, just pull it in.

**Comment by signal-intrusion** [comment]
@akidee there is no license specified in the README or in the package.json file.

**Comment by akidee** [comment]
Updated to MIT license, tagged as v0.2.1, published to NPM.
